import { ICountry } from "./interfaces/country.interface";

export const countries: ICountry[] = [
   { alphaIso3: 'AFG', alphaIso2: 'AF', countryName: 'Afghanistan' },
   { alphaIso3: 'ALB', alphaIso2: 'AL', countryName: 'Albania' },
   { alphaIso3: 'DZA', alphaIso2: 'DZ', countryName: 'Algeria' },
   { alphaIso3: 'ASM', alphaIso2: 'AS', countryName: 'American Samoa' },
   { alphaIso3: 'AND', alphaIso2: 'AD', countryName: 'Andorra' },
   { alphaIso3: 'AGO', alphaIso2: 'AO', countryName: 'Angola' },
   { alphaIso3: 'AIA', alphaIso2: 'AI', countryName: 'Anguilla' },
   {
      alphaIso3: 'ATG',
      alphaIso2: 'AG',
      countryName: 'Antigua and Barbuda'
   },
   { alphaIso3: 'ARG', alphaIso2: 'AR', countryName: 'Argentina' },
   { alphaIso3: 'ARM', alphaIso2: 'AM', countryName: 'Armenia' },
   { alphaIso3: 'ABW', alphaIso2: 'AW', countryName: 'Aruba' },
   { alphaIso3: 'AUS', alphaIso2: 'AU', countryName: 'Australia' },
   { alphaIso3: 'AUT', alphaIso2: 'AT', countryName: 'Austria' },
   { alphaIso3: 'AZE', alphaIso2: 'AZ', countryName: 'Azerbaijan' },
   { alphaIso3: 'BHS', alphaIso2: 'BS', countryName: 'The Bahamas' },
   { alphaIso3: 'BHR', alphaIso2: 'BH', countryName: 'Bahrain' },
   { alphaIso3: 'BGD', alphaIso2: 'BD', countryName: 'Bangladesh' },
   { alphaIso3: 'BRB', alphaIso2: 'BB', countryName: 'Barbados' },
   { alphaIso3: 'BLR', alphaIso2: 'BY', countryName: 'Belarus' },
   { alphaIso3: 'BEL', alphaIso2: 'BE', countryName: 'Belgium' },
   { alphaIso3: 'BLZ', alphaIso2: 'BZ', countryName: 'Belize' },
   { alphaIso3: 'BEN', alphaIso2: 'BJ', countryName: 'Benin' },
   { alphaIso3: 'BMU', alphaIso2: 'BM', countryName: 'Bermuda' },
   { alphaIso3: 'BTN', alphaIso2: 'BT', countryName: 'Bhutan' },
   { alphaIso3: 'BOL', alphaIso2: 'BO', countryName: 'Bolivia' },
   {
      alphaIso3: 'BIH',
      alphaIso2: 'BA',
      countryName: 'Bosnia and Herzegovina'
   },
   { alphaIso3: 'BWA', alphaIso2: 'BW', countryName: 'Botswana' },
   { alphaIso3: 'BRA', alphaIso2: 'BR', countryName: 'Brazil' },
   {
      alphaIso3: 'VGB',
      alphaIso2: 'VG',
      countryName: 'British Virgin Islands'
   },
   { alphaIso3: 'BRN', alphaIso2: 'BN', countryName: 'Brunei' },
   { alphaIso3: 'BGR', alphaIso2: 'BG', countryName: 'Bulgaria' },
   { alphaIso3: 'BFA', alphaIso2: 'BF', countryName: 'Burkina Faso' },
   { alphaIso3: 'BDI', alphaIso2: 'BI', countryName: 'Burundi' },
   { alphaIso3: 'KHM', alphaIso2: 'KH', countryName: 'Cambodia' },
   { alphaIso3: 'CMR', alphaIso2: 'CM', countryName: 'Cameroon' },
   { alphaIso3: 'CAN', alphaIso2: 'CA', countryName: 'Canada' },
   { alphaIso3: 'CPV', alphaIso2: 'CV', countryName: 'Cape Verde' },
   { alphaIso3: 'CYM', alphaIso2: 'KY', countryName: 'Cayman Islands' },
   {
      alphaIso3: 'CAF',
      alphaIso2: 'CF',
      countryName: 'Central African Republic'
   },
   { alphaIso3: 'TCD', alphaIso2: 'TD', countryName: 'Chad' },
   { alphaIso3: 'CHL', alphaIso2: 'CL', countryName: 'Chile' },
   { alphaIso3: 'CHN', alphaIso2: 'CN', countryName: 'China' },
   {
      alphaIso3: 'CXR',
      alphaIso2: 'CX',
      countryName: 'Christmas Island'
   },
   {
      alphaIso3: 'CCK',
      alphaIso2: 'CC',
      countryName: 'Cocos (Keeling) Islands'
   },
   { alphaIso3: 'COL', alphaIso2: 'CO', countryName: 'Colombia' },
   { alphaIso3: 'COM', alphaIso2: 'KM', countryName: 'Comoros' },
   {
      alphaIso3: 'COG',
      alphaIso2: 'CG',
      countryName: 'Republic of the Congo'
   },
   { alphaIso3: 'COK', alphaIso2: 'CK', countryName: 'Cook Islands' },
   { alphaIso3: 'CRI', alphaIso2: 'CR', countryName: 'Costa Rica' },
   { alphaIso3: 'CIV', alphaIso2: 'CI', countryName: "Cote d'Ivoire" },
   { alphaIso3: 'HRV', alphaIso2: 'HR', countryName: 'Croatia' },
   { alphaIso3: 'CUB', alphaIso2: 'CU', countryName: 'Cuba' },
   { alphaIso3: 'CYP', alphaIso2: 'CY', countryName: 'Cyprus' },
   { alphaIso3: 'CZE', alphaIso2: 'CZ', countryName: 'Czech Republic' },
   { alphaIso3: 'DNK', alphaIso2: 'DK', countryName: 'Denmark' },
   { alphaIso3: 'DJI', alphaIso2: 'DJ', countryName: 'Djibouti' },
   { alphaIso3: 'DMA', alphaIso2: 'DM', countryName: 'Dominica' },
   {
      alphaIso3: 'DOM',
      alphaIso2: 'DO',
      countryName: 'Dominican Republic'
   },
   { alphaIso3: 'ECU', alphaIso2: 'EC', countryName: 'Ecuador' },
   { alphaIso3: 'EGY', alphaIso2: 'EG', countryName: 'Egypt' },
   { alphaIso3: 'SLV', alphaIso2: 'SV', countryName: 'El Salvador' },
   {
      alphaIso3: 'GNQ',
      alphaIso2: 'GQ',
      countryName: 'Equatorial Guinea'
   },
   { alphaIso3: 'ERI', alphaIso2: 'ER', countryName: 'Eritrea' },
   { alphaIso3: 'EST', alphaIso2: 'EE', countryName: 'Estonia' },
   { alphaIso3: 'ETH', alphaIso2: 'ET', countryName: 'Ethiopia' },
   {
      alphaIso3: 'FLK',
      alphaIso2: 'FK',
      countryName: 'Falkland Islands (Islas Malvinas)'
   },
   { alphaIso3: 'FRO', alphaIso2: 'FO', countryName: 'Faroe Islands' },
   { alphaIso3: 'FJI', alphaIso2: 'FJ', countryName: 'Fiji' },
   { alphaIso3: 'FIN', alphaIso2: 'FI', countryName: 'Finland' },
   { alphaIso3: 'FRA', alphaIso2: 'FR', countryName: 'France' },
   { alphaIso3: 'GUF', alphaIso2: 'GF', countryName: 'French Guiana' },
   {
      alphaIso3: 'PYF',
      alphaIso2: 'PF',
      countryName: 'French Polynesia'
   },
   { alphaIso3: 'GAB', alphaIso2: 'GA', countryName: 'Gabon' },
   { alphaIso3: 'GMB', alphaIso2: 'GM', countryName: 'The Gambia' },
   { alphaIso3: 'GEO', alphaIso2: 'GE', countryName: 'Georgia' },
   { alphaIso3: 'DEU', alphaIso2: 'DE', countryName: 'Germany' },
   { alphaIso3: 'GHA', alphaIso2: 'GH', countryName: 'Ghana' },
   { alphaIso3: 'GIB', alphaIso2: 'GI', countryName: 'Gibraltar' },
   { alphaIso3: 'GRC', alphaIso2: 'GR', countryName: 'Greece' },
   { alphaIso3: 'GRL', alphaIso2: 'GL', countryName: 'Greenland' },
   { alphaIso3: 'GRD', alphaIso2: 'GD', countryName: 'Grenada' },
   { alphaIso3: 'GLP', alphaIso2: 'GP', countryName: 'Guadeloupe' },
   { alphaIso3: 'GUM', alphaIso2: 'GU', countryName: 'Guam' },
   { alphaIso3: 'GTM', alphaIso2: 'GT', countryName: 'Guatemala' },
   { alphaIso3: 'GIN', alphaIso2: 'GN', countryName: 'Guinea' },
   { alphaIso3: 'GNB', alphaIso2: 'GW', countryName: 'Guinea-Bissau' },
   { alphaIso3: 'GUY', alphaIso2: 'GY', countryName: 'Guyana' },
   { alphaIso3: 'HTI', alphaIso2: 'HT', countryName: 'Haiti' },
   {
      alphaIso3: 'VAT',
      alphaIso2: 'VA',
      countryName: 'Holy See (Vatican City)'
   },
   { alphaIso3: 'HND', alphaIso2: 'HN', countryName: 'Honduras' },
   { alphaIso3: 'HUN', alphaIso2: 'HU', countryName: 'Hungary' },
   { alphaIso3: 'ISL', alphaIso2: 'IS', countryName: 'Iceland' },
   { alphaIso3: 'IND', alphaIso2: 'IN', countryName: 'India' },
   { alphaIso3: 'IDN', alphaIso2: 'ID', countryName: 'Indonesia' },
   { alphaIso3: 'IRN', alphaIso2: 'IR', countryName: 'Iran' },
   { alphaIso3: 'IRQ', alphaIso2: 'IQ', countryName: 'Iraq' },
   { alphaIso3: 'IRL', alphaIso2: 'IE', countryName: 'Ireland' },
   { alphaIso3: 'ISR', alphaIso2: 'IL', countryName: 'Israel' },
   { alphaIso3: 'ITA', alphaIso2: 'IT', countryName: 'Italy' },
   { alphaIso3: 'JAM', alphaIso2: 'JM', countryName: 'Jamaica' },
   { alphaIso3: 'JPN', alphaIso2: 'JP', countryName: 'Japan' },
   { alphaIso3: 'JOR', alphaIso2: 'JO', countryName: 'Jordan' },
   { alphaIso3: 'KAZ', alphaIso2: 'KZ', countryName: 'Kazakhstan' },
   { alphaIso3: 'KEN', alphaIso2: 'KE', countryName: 'Kenya' },
   { alphaIso3: 'KIR', alphaIso2: 'KI', countryName: 'Kiribati' },
   { alphaIso3: 'PRK', alphaIso2: 'KP', countryName: 'North Korea' },
   { alphaIso3: 'KOR', alphaIso2: 'KR', countryName: 'South Korea' },
   { alphaIso3: 'KWT', alphaIso2: 'KW', countryName: 'Kuwait' },
   { alphaIso3: 'KGZ', alphaIso2: 'KG', countryName: 'Kyrgyzstan' },
   { alphaIso3: 'LAO', alphaIso2: 'LA', countryName: 'Laos' },
   { alphaIso3: 'LVA', alphaIso2: 'LV', countryName: 'Latvia' },
   { alphaIso3: 'LBN', alphaIso2: 'LB', countryName: 'Lebanon' },
   { alphaIso3: 'LSO', alphaIso2: 'LS', countryName: 'Lesotho' },
   { alphaIso3: 'LBR', alphaIso2: 'LR', countryName: 'Liberia' },
   { alphaIso3: 'LBY', alphaIso2: 'LY', countryName: 'Libya' },
   { alphaIso3: 'LIE', alphaIso2: 'LI', countryName: 'Liechtenstein' },
   { alphaIso3: 'LTU', alphaIso2: 'LT', countryName: 'Lithuania' },
   { alphaIso3: 'LUX', alphaIso2: 'LU', countryName: 'Luxembourg' },
   { alphaIso3: 'MKD', alphaIso2: 'MK', countryName: 'North Macedonia' },
   { alphaIso3: 'MDG', alphaIso2: 'MG', countryName: 'Madagascar' },
   { alphaIso3: 'MWI', alphaIso2: 'MW', countryName: 'Malawi' },
   { alphaIso3: 'MYS', alphaIso2: 'MY', countryName: 'Malaysia' },
   { alphaIso3: 'MDV', alphaIso2: 'MV', countryName: 'Maldives' },
   { alphaIso3: 'MLI', alphaIso2: 'ML', countryName: 'Mali' },
   { alphaIso3: 'MLT', alphaIso2: 'MT', countryName: 'Malta' },
   { alphaIso3: 'IMN', alphaIso2: 'IM', countryName: 'Isle of Man' },
   {
      alphaIso3: 'MHL',
      alphaIso2: 'MH',
      countryName: 'Marshall Islands'
   },
   { alphaIso3: 'MTQ', alphaIso2: 'MQ', countryName: 'Martinique' },
   { alphaIso3: 'MRT', alphaIso2: 'MR', countryName: 'Mauritania' },
   { alphaIso3: 'MUS', alphaIso2: 'MU', countryName: 'Mauritius' },
   { alphaIso3: 'MYT', alphaIso2: 'YT', countryName: 'Mayotte' },
   { alphaIso3: 'MEX', alphaIso2: 'MX', countryName: 'Mexico' },
   {
      alphaIso3: 'FSM',
      alphaIso2: 'FM',
      countryName: 'Federated States of Micronesia'
   },
   { alphaIso3: 'MDA', alphaIso2: 'MD', countryName: 'Moldova' },
   { alphaIso3: 'MCO', alphaIso2: 'MC', countryName: 'Monaco' },
   { alphaIso3: 'MNG', alphaIso2: 'MN', countryName: 'Mongolia' },
   { alphaIso3: 'MSR', alphaIso2: 'MS', countryName: 'Montserrat' },
   { alphaIso3: 'MAR', alphaIso2: 'MA', countryName: 'Morocco' },
   { alphaIso3: 'MOZ', alphaIso2: 'MZ', countryName: 'Mozambique' },
   { alphaIso3: 'MMR', alphaIso2: 'MM', countryName: 'Myanmar (Burma)' },
   { alphaIso3: 'NAM', alphaIso2: 'NA', countryName: 'Namibia' },
   { alphaIso3: 'NRU', alphaIso2: 'NR', countryName: 'Nauru' },
   { alphaIso3: 'NPL', alphaIso2: 'NP', countryName: 'Nepal' },
   { alphaIso3: 'NLD', alphaIso2: 'NL', countryName: 'Netherlands' },
   {
      alphaIso3: 'ANT',
      alphaIso2: 'AN',
      countryName: 'Netherlands Antilles'
   },
   { alphaIso3: 'NCL', alphaIso2: 'NC', countryName: 'New Caledonia' },
   { alphaIso3: 'NZL', alphaIso2: 'NZ', countryName: 'New Zealand' },
   { alphaIso3: 'NIC', alphaIso2: 'NI', countryName: 'Nicaragua' },
   { alphaIso3: 'NER', alphaIso2: 'NE', countryName: 'Niger' },
   { alphaIso3: 'NGA', alphaIso2: 'NG', countryName: 'Nigeria' },
   { alphaIso3: 'NIU', alphaIso2: 'NU', countryName: 'Niue' },
   { alphaIso3: 'NFK', alphaIso2: 'NF', countryName: 'Norfolk Island' },
   {
      alphaIso3: 'MNP',
      alphaIso2: 'MP',
      countryName: 'Northern Mariana Islands'
   },
   { alphaIso3: 'NOR', alphaIso2: 'NO', countryName: 'Norway' },
   { alphaIso3: 'OMN', alphaIso2: 'OM', countryName: 'Oman' },
   { alphaIso3: 'PAK', alphaIso2: 'PK', countryName: 'Pakistan' },
   { alphaIso3: 'PLW', alphaIso2: 'PW', countryName: 'Palau' },
   {
      alphaIso3: 'PSE',
      alphaIso2: 'PS',
      countryName: 'Palestinian Territory'
   },
   { alphaIso3: 'PAN', alphaIso2: 'PA', countryName: 'Panama' },
   {
      alphaIso3: 'PNG',
      alphaIso2: 'PG',
      countryName: 'Papua New Guinea'
   },
   { alphaIso3: 'PRY', alphaIso2: 'PY', countryName: 'Paraguay' },
   { alphaIso3: 'PER', alphaIso2: 'PE', countryName: 'Peru' },
   { alphaIso3: 'PHL', alphaIso2: 'PH', countryName: 'Philippines' },
   {
      alphaIso3: 'PCN',
      alphaIso2: 'PN',
      countryName: 'Pitcairn Islands'
   },
   { alphaIso3: 'POL', alphaIso2: 'PL', countryName: 'Poland' },
   { alphaIso3: 'PRT', alphaIso2: 'PT', countryName: 'Portugal' },
   { alphaIso3: 'PRI', alphaIso2: 'PR', countryName: 'Puerto Rico' },
   { alphaIso3: 'QAT', alphaIso2: 'QA', countryName: 'Qatar' },
   { alphaIso3: 'REU', alphaIso2: 'RE', countryName: 'Reunion' },
   { alphaIso3: 'ROU', alphaIso2: 'RO', countryName: 'Romania' },
   { alphaIso3: 'RUS', alphaIso2: 'RU', countryName: 'Russia' },
   { alphaIso3: 'RWA', alphaIso2: 'RW', countryName: 'Rwanda' },
   {
      alphaIso3: 'KNA',
      alphaIso2: 'KN',
      countryName: 'Saint Kitts and Nevis'
   },
   { alphaIso3: 'LCA', alphaIso2: 'LC', countryName: 'Saint Lucia' },
   {
      alphaIso3: 'SPM',
      alphaIso2: 'PM',
      countryName: 'Saint Pierre and Miquelon'
   },
   {
      alphaIso3: 'VCT',
      alphaIso2: 'VC',
      countryName: 'Saint Vincent and the Grenadines'
   },
   { alphaIso3: 'SMR', alphaIso2: 'SM', countryName: 'San Marino' },
   {
      alphaIso3: 'STP',
      alphaIso2: 'ST',
      countryName: 'Sao Tome and Principe'
   },
   { alphaIso3: 'SAU', alphaIso2: 'SA', countryName: 'Saudi Arabia' },
   { alphaIso3: 'SEN', alphaIso2: 'SN', countryName: 'Senegal' },
   { alphaIso3: 'SYC', alphaIso2: 'SC', countryName: 'Seychelles' },
   { alphaIso3: 'SLE', alphaIso2: 'SL', countryName: 'Sierra Leone' },
   { alphaIso3: 'SGP', alphaIso2: 'SG', countryName: 'Singapore' },
   { alphaIso3: 'SVK', alphaIso2: 'SK', countryName: 'Slovakia' },
   { alphaIso3: 'SVN', alphaIso2: 'SI', countryName: 'Slovenia' },
   { alphaIso3: 'SLB', alphaIso2: 'SB', countryName: 'Solomon Islands' },
   { alphaIso3: 'SOM', alphaIso2: 'SO', countryName: 'Somalia' },
   { alphaIso3: 'ZAF', alphaIso2: 'ZA', countryName: 'South Africa' },
   { alphaIso3: 'ESP', alphaIso2: 'ES', countryName: 'Spain' },
   { alphaIso3: 'LKA', alphaIso2: 'LK', countryName: 'Sri Lanka' },
   { alphaIso3: 'SDN', alphaIso2: 'SD', countryName: 'Sudan' },
   { alphaIso3: 'SUR', alphaIso2: 'SR', countryName: 'Suriname' },
   { alphaIso3: 'SJM', alphaIso2: 'SJ', countryName: 'Svalbard' },
   { alphaIso3: 'SWZ', alphaIso2: 'SZ', countryName: 'Eswatini' },
   { alphaIso3: 'SWE', alphaIso2: 'SE', countryName: 'Sweden' },
   { alphaIso3: 'CHE', alphaIso2: 'CH', countryName: 'Switzerland' },
   { alphaIso3: 'SYR', alphaIso2: 'SY', countryName: 'Syria' },
   { alphaIso3: 'TWN', alphaIso2: 'TW', countryName: 'Taiwan' },
   { alphaIso3: 'TJK', alphaIso2: 'TJ', countryName: 'Tajikistan' },
   { alphaIso3: 'TZA', alphaIso2: 'TZ', countryName: 'Tanzania' },
   { alphaIso3: 'THA', alphaIso2: 'TH', countryName: 'Thailand' },
   { alphaIso3: 'TGO', alphaIso2: 'TG', countryName: 'Togo' },
   { alphaIso3: 'TKL', alphaIso2: 'TK', countryName: 'Tokelau' },
   { alphaIso3: 'TON', alphaIso2: 'TO', countryName: 'Tonga' },
   {
      alphaIso3: 'TTO',
      alphaIso2: 'TT',
      countryName: 'Trinidad and Tobago'
   },
   { alphaIso3: 'TUN', alphaIso2: 'TN', countryName: 'Tunisia' },
   { alphaIso3: 'TUR', alphaIso2: 'TR', countryName: 'Turkey' },
   { alphaIso3: 'TKM', alphaIso2: 'TM', countryName: 'Turkmenistan' },
   {
      alphaIso3: 'TCA',
      alphaIso2: 'TC',
      countryName: 'Turks and Caicos Islands'
   },
   { alphaIso3: 'TUV', alphaIso2: 'TV', countryName: 'Tuvalu' },
   { alphaIso3: 'UGA', alphaIso2: 'UG', countryName: 'Uganda' },
   { alphaIso3: 'UKR', alphaIso2: 'UA', countryName: 'Ukraine' },
   {
      alphaIso3: 'ARE',
      alphaIso2: 'AE',
      countryName: 'United Arab Emirates'
   },
   { alphaIso3: 'GBR', alphaIso2: 'GB', countryName: 'United Kingdom' },
   { alphaIso3: 'USA', alphaIso2: 'US', countryName: 'United States' },
   {
      alphaIso3: 'UMI',
      alphaIso2: 'UM',
      countryName: 'United States Minor Outlying Islands'
   },
   { alphaIso3: 'URY', alphaIso2: 'UY', countryName: 'Uruguay' },
   { alphaIso3: 'UZB', alphaIso2: 'UZ', countryName: 'Uzbekistan' },
   { alphaIso3: 'VUT', alphaIso2: 'VU', countryName: 'Vanuatu' },
   { alphaIso3: 'VEN', alphaIso2: 'VE', countryName: 'Venezuela' },
   { alphaIso3: 'VNM', alphaIso2: 'VN', countryName: 'Vietnam' },
   { alphaIso3: 'VIR', alphaIso2: 'VI', countryName: 'Virgin Islands' },
   {
      alphaIso3: 'WLF',
      alphaIso2: 'WF',
      countryName: 'Wallis and Futuna'
   },
   { alphaIso3: 'ESH', alphaIso2: 'EH', countryName: 'Western Sahara' },
   { alphaIso3: 'WSM', alphaIso2: 'WS', countryName: 'Western Samoa' },
   { alphaIso3: 'YEM', alphaIso2: 'YE', countryName: 'Yemen' },
   {
      alphaIso3: 'COD',
      alphaIso2: 'CD',
      countryName: 'Democratic Republic of the Congo'
   },
   { alphaIso3: 'ZMB', alphaIso2: 'ZM', countryName: 'Zambia' },
   { alphaIso3: 'ZWE', alphaIso2: 'ZW', countryName: 'Zimbabwe' },
   { alphaIso3: 'HKG', alphaIso2: 'HK', countryName: 'Hong Kong' },
   { alphaIso3: 'MAC', alphaIso2: 'MO', countryName: 'Macau' },
   { alphaIso3: 'ATA', alphaIso2: 'AQ', countryName: 'Antarctica' },
   { alphaIso3: 'BVT', alphaIso2: 'BV', countryName: 'Bouvet Island' },
   {
      alphaIso3: 'IOT',
      alphaIso2: 'IO',
      countryName: 'British Indian Ocean Territory'
   },
   {
      alphaIso3: 'ATF',
      alphaIso2: 'TF',
      countryName: 'French Southern and Antarctic Lands'
   },
   {
      alphaIso3: 'HMD',
      alphaIso2: 'HM',
      countryName: 'Heard Island and McDonald Islands'
   },
   { alphaIso3: 'SHN', alphaIso2: 'SH', countryName: 'Saint Helena' },
   {
      alphaIso3: 'SGS',
      alphaIso2: 'GS',
      countryName: 'South Georgia and the South Sandwich Islands'
   },
   { alphaIso3: 'GGY', alphaIso2: 'GG', countryName: 'Guernsey' },
   { alphaIso3: 'SRB', alphaIso2: 'RS', countryName: 'Serbia' },
   {
      alphaIso3: 'BLM',
      alphaIso2: 'BL',
      countryName: 'Saint Barthélemy'
   },
   { alphaIso3: 'MNE', alphaIso2: 'ME', countryName: 'Montenegro' },
   { alphaIso3: 'JEY', alphaIso2: 'JE', countryName: 'Jersey' },
   { alphaIso3: 'CUW', alphaIso2: 'CW', countryName: 'Curaçao' },
   { alphaIso3: 'MAF', alphaIso2: 'MF', countryName: 'Saint Martin' },
   { alphaIso3: 'SXM', alphaIso2: 'SX', countryName: 'Sint Maarten' },
   { alphaIso3: 'TLS', alphaIso2: 'TL', countryName: 'Timor-Leste' },
   { alphaIso3: 'SSD', alphaIso2: 'SS', countryName: 'South Sudan' },
   { alphaIso3: 'ALA', alphaIso2: 'AX', countryName: 'Åland Islands' },
   { alphaIso3: 'BES', alphaIso2: 'BQ', countryName: 'Bonaire' },
   {
      alphaIso3: 'XKS',
      alphaIso2: 'XK',
      countryName: 'Republic of Kosovo'
   }
];
